### HelloController

# @no-log
GET http://localhost:8080/hello

### ChatController

# @prompt msg
GET http://localhost:8080/chat/chat?msg={{msg}}

###

# @prompt msg
GET http://localhost:8080/chat/streamChat?msg={"你好"}


### QuestionController

# @name generateQuestion
POST http://localhost:8080/question/generateQuestion
Content-Type: application/json

{
  "question": "java",
  "questionNum": 1
}

###

# @name asyncGenerateQuestion
POST http://localhost:8080/question/asyncGenerateQuestion
Content-Type: application/json

{
  "question": "java",
  "questionNum": 1
}

###

@generateId=24c89832-5be0-4df9-9210-86b9487c8e99
GET http://localhost:8080/question/question/{{generateId}}